# Generated by Django 4.2 on 2024-06-04 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_image_annotated_alter_image_mode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelmetric',
            old_name='entry_timestamp',
            new_name='created_at',
        ),
    ]
