# Generated by Django 4.2 on 2024-06-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_rename_entry_timestamp_modelmetric_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='classes',
            field=models.JSONField(default=[0]),
        ),
    ]
