# Generated by Django 4.2 on 2024-06-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_annotation_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='classes',
            field=models.JSONField(default=0),
        ),
    ]
