# Generated by Django 4.2 on 2024-06-06 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_annotation_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='classes',
        ),
    ]
